apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iooding-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Viktorpav/talos-iooding.git
    targetRevision: main
    path: talos/iooding-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: iooding
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
